apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app-deployment
spec:
  selector:
    matchLabels:
      app: bank-app
  replicas: 2
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          image: semever/bank-app:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
